### ISSUE TITLE
Is there a way to set tagName = "" on the ember component?

### ISSUE THREAD

**Issue by vlascik** [alexlafroscia/ember-react-components#17]
This might be more of a question, but I wasn't able to find an answer to this - is there a way to set `tagName` on the component returned by the `@WithEmberSupport` decorator, so that the React components are not wrapped in extraneous divs? I can't seem to find a way, using `@tagName('')` from `ember-decorators` doesn't seem to work here.

**Comment by alexlafroscia** [comment]
I would love to be able to do this, but unfortunately I cannot ☹️ 

The way this basically works, when you wrap a React component with the decorator for Ember compatibility, you take the component's wrapper element (which would go away with `tagName = ''`) and use that as the node to mount the React tree at.

Without a tag name, you have no way to mount that tree. I looked into trying to find the closest parent node and using that as the React tree root, but without an element for the component itself there's no safe way to access the component's location in the DOM to find that parent.

I would love to keep this open, but I'm going to close this since in Ember's current state this is just not possible.

However, I am keeping a close eye on the component manager RFCs that are being worked on that will allow for lower-level component base classes than what is currently available, and looking into whether those APIs will allow me to make the decorator even better and avoid that root element!
